CREATE TABLE IF NOT EXISTS MODEL(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION TEXT,
    CLASS VARCHAR(30) NOT NULL,
    BRAND VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(30) NOT NULL,
    LINE_UP VARCHAR(30) NOT NULL
);

